name: Build project 🏗️🚧👷

on: [pull_request: { branches: ['main', 'dev'], status: 'approved' }]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.0
      - uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - name: Create release
  uses: actions/create-release@v1
  with:
    tag_name: ${{ github.ref }}
    target_commitish: ${{ github.ref }}
    name: ${{ github.event.head_commit.message }}
    description: Release of ${{ github.ref }}
    draft: false
    prerelease: false
    upload_artifacts: true
    artifacts:
      - name: Build-${{ matrix.targetPlatform }}
        path: build/${{ matrix.targetPlatform }}"