name: Assign Label to Issue in Project

on:
  issues:
    types:
      - opened

jobs:
  assign-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Assign label if issue is in 'prg1' project
      run: |
        issue_number=${{ github.event.issue.number }}
        projects=$(curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/projects \
          --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Accept: application/vnd.github.inertia-preview+json')
        
        is_in_planner=$(echo "$projects" | jq '.[] | select(.name=="PRG1")')
        
        if [[ ! -z "$is_in_planner" ]]; then
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/labels \
          --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3+json' \
          --data '{
            "labels": ["PRG1"]
          }'
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
