name: Publish test results
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Unity
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Unity Test Runner
        run: npm i @nativescript/unit-test-runner

      - name: Run tests
        run: unity-test-runner

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results