name: Run Unity tests
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Unity
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Unity Test Framework
        run: npm install -g unity-test-framework

      - name: Run tests
        run: unity-test-framework